name: Build

on:
  - pull_request
  - push
  
jobs:
  build-native:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        ocaml-version:
          - 4.11.1

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}

      - run: opam pin add . --no-action
      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build
      - run: opam exec -- dune runtest

  build-latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Latex
        uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make
            make tex
